### ISSUE TITLE
App crashes frequently using edge detection 

### ISSUE THREAD

**Issue by PranayRaj2801** [sawankumarbundelkhandi/edge_detection#30]
Fatal Exception: java.lang.RuntimeException
takePicture failed

android.hardware.Camera.native_takePicture (Camera.java)
android.hardware.Camera.takePicture (Camera.java:1564)
android.hardware.Camera.takePicture (Camera.java:1506)
com.sample.edgedetection.scan.ScanPresenter$shut$1.onAutoFocus (ScanPresenter.kt:67)
android.hardware.Camera$EventHandler.handleMessage (Camera.java:1238)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7860)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1075)

**Comment by sawankumarbundelkhandi** [comment]
It looks like this - https://stackoverflow.com/questions/21723557/java-lang-runtimeexception-takepicture-failed. Are you clicking the capture button multiple times?

Also, Make sure the permission to camera is given. In next release I will handle that in the plugin itself to ask for permission if not given.

**Comment by sawankumarbundelkhandi** [comment]
This is fixed in @vmwsree https://github.com/sawankumarbundelkhandi/edge_detection/pull/34. I will try to merge it soon.

**Comment by jusuf-el** [comment]
Adding android:requestLegacyExternalStorage="true" to Manifest file under <application... fixed my issue on Android. Still facing the crashing on iOS device.

**Comment by sawankumarbundelkhandi** [comment]
@PranayRaj2801 this is fixed and I will release it soon on pub.
