### ISSUE TITLE
Pod WeScan version Issue

### ISSUE THREAD

**Issue by EdisonTKPcom** [sawankumarbundelkhandi/edge_detection#5]
Xcode's output:
↳
    edge_detection/example/ios/Pods/WeScan/WeScan/ImageScannerController.swift:125:14: error: 'bringSubviewToFront' has been renamed to 'bringSubview(toFront:)'
            view.bringSubviewToFront(blackFlashView)
                 ^~~~~~~~~~~~~~~~~~~
                 bringSubview        toFront: 
    UIKit.UIView:17:15: note: 'bringSubviewToFront' was obsoleted in Swift 3
        open func bringSubviewToFront(_ view: UIView)
                  ^
    edge_detection/example/ios/Pods/WeScan/WeScan/Common/QuadrilateralView.swift:63:29: error: 'bringSubviewToFront' has been renamed to 'bringSubview(toFront:)'
                isHighlighted ? bringSubviewToFront(quadView) : sendSubviewToBack(quadView)
                                ^~~~~~~~~~~~~~~~~~~
                                bringSubview        toFront: 
    UIKit.UIView:17:15: note: 'bringSubviewToFront' was obsoleted in Swift 3
        open func bringSubviewToFront(_ view: UIView)
                  ^
    edge_detection/example/ios/Pods/WeScan/WeScan/Common/QuadrilateralView.swift:63:61: error: 'sendSubviewToBack' has been renamed to 'sendSubview(toBack:)'
                isHighlighted ? bringSubviewToFront(quadView) : sendSubviewToBack(quadView)
                                                                ^~~~~~~~~~~~~~~~~
                                                                sendSubview       toBack: 
    UIKit.UIView:20:15: note: 'sendSubviewToBack' was obsoleted in Swift 3
        open func sendSubviewToBack(_ view: UIView)
                  ^
    edge_detection/example/ios/Pods/WeScan/WeScan/Scan/ScannerViewController.swift:65:33: error: 'init(style:)' has been renamed to 'init(activityIndicatorStyle:)'
            let activityIndicator = UIActivityIndicatorView(style: .gray)
                                    ^                       ~~~~~
                                                            activityIndicatorStyle
    UIKit.UIActivityIndicatorView:6:12: note: 'init(style:)' was introduced in Swift 4.2
        public init(style: UIActivityIndicatorViewStyle)
               ^
    edge_detection/example/ios/Pods/WeScan/WeScan/Scan/ScannerViewController.swift:65:33: error: 'init(style:)' has been renamed to 'init(activityIndicatorStyle:)'
            let activityIndicator = UIActivityIndicatorView(style: .gray)
                                    ^                       ~~~~~
                                                            activityIndicatorStyle
    UIKit.UIActivityIndicatorView:6:12: note: 'init(style:)' was introduced in Swift 4.2
        public init(style: UIActivityIndicatorViewStyle)
               ^
    edge_detection/example/ios/Pods/WeScan/WeScan/Scan/ScannerViewController.swift:102:45: error: 'sendSubviewToBack' has been renamed to 'sendSubview(toBack:)'
            navigationController?.navigationBar.sendSubviewToBack(visualEffectView)
                                                ^~~~~~~~~~~~~~~~~
                                                sendSubview       toBack: 
    UIKit.UIView:20:15: note: 'sendSubviewToBack' was obsoleted in Swift 3
        open func sendSubviewToBack(_ view: UIView)
                  ^
    edge_detection/example/ios/Pods/WeScan/WeScan/Scan/ShutterButton.swift:38:31: error: type 'UIAccessibilityTraits' (aka 'UInt64') has no member 'button'
            accessibilityTraits = UIAccessibilityTraits.button
                                  ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~
    edge_detection/example/ios/Pods/WeScan/WeScan/Scan/ShutterButton.swift:74:30: error: type 'CAMediaTimingFillMode' (aka 'NSString') has no member 'forwards'
            animation.fillMode = CAMediaTimingFillMode.forwards

**Comment by brap242** [comment]
Hi, 

i have simmilar problem in my flutter project. I got following output:

      A AppCenter
      A Flutter
      A MTBBarcodeScanner
      A WeScan
      A appcenter
      A appcenter_analytics
      A appcenter_crashes
      A barcode_scan
      A edge_detection
      A flutter_secure_storage
      A fluttertoast
      A image_picker
    Downloading dependencies
    -> Installing AppCenter (1.13.2)
      > Copying AppCenter from `/Users/michal/Library/Caches/CocoaPods/Pods/Release/AppCenter/1.13.2-bce7f` to `Pods/AppCenter`
    -> Installing Flutter (1.0.0)
    -> Installing MTBBarcodeScanner (5.0.11)
      > Copying MTBBarcodeScanner from `/Users/michal/Library/Caches/CocoaPods/Pods/Release/MTBBarcodeScanner/5.0.11-f453b` to `Pods/MTBBarcodeScanner`
    -> Installing WeScan (1.1.0)
      > Copying WeScan from `/Users/michal/Library/Caches/CocoaPods/Pods/Release/WeScan/1.1.0-7ebe0` to `Pods/WeScan`
    -> Installing appcenter (0.0.1)
    -> Installing appcenter_analytics (0.0.1)
    -> Installing appcenter_crashes (0.0.1)
    -> Installing barcode_scan (0.0.1)
    -> Installing edge_detection (1.0.2)
    -> Installing flutter_secure_storage (3.2.0)
    -> Installing fluttertoast (0.0.2)
    -> Installing image_picker (0.0.1)
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:
    - `WeScan` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `edge_detection` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:115:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.0/libexec/bin/pod:22:in `<main>'
Error running pod install
Exited (sigterm)

**Comment by lurkerCha** [comment]
I fixed mine by following this link:
https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482

**Comment by sawankumarbundelkhandi** [comment]
@EdisonTKPcom if @lurkerCha comment has not fixed your issue then reopen it.
